spring.datasource.url=jdbc:mysql://mysql:3306/hibernatedb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=user1
spring.datasource.password=user@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=5
